nome = input("DIgite seu nome : ")
idade= int(input("Digite sua idade: "))
salario = float(input("Digite seu salario: "))
print(f'Olá {nome}, você tem {idade} anos, e seu salario é {salario:.2f}')
aumento = float(input("Digite o valor do aumento:  "))
aumentoA =salario +(salario*aumento/100)
print(f"Novo salario: {aumentoA:.2f}, e salario antigo é {salario:.2f}")